name: Checks and tests

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, reopened, edited, synchronize, ready_for_review ]

jobs:
  test:
    name: Checks and tests
    runs-on: ubuntu-latest
    
    env:
      MIX_ENV: test
      ELIXIR_VERSION: '1.19.3'
      OTP_VERSION: '28.1'
      SCENIC_LOCAL_TARGET: 'glfw'
      MIX_TARGET: 'host'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ env.ELIXIR_VERSION }}
        otp-version: ${{ env.OTP_VERSION }}
    
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-${{ env.ELIXIR_VERSION }}-${{ env.OTP_VERSION }}-mix-${{ env.MIX_TARGET }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-${{ env.ELIXIR_VERSION }}-${{ env.OTP_VERSION }}-mix-${{ env.MIX_TARGET }}-
    
    - name: Install dependencies
      run: mix deps.get

    - name: Restore build cache
      uses: actions/cache@v4
      with:
        path: _build
        key: ${{ runner.os }}-${{ env.ELIXIR_VERSION }}-${{ env.OTP_VERSION }}-build-${{ env.MIX_TARGET }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.ELIXIR_VERSION }}-${{ env.OTP_VERSION }}-build-${{ env.MIX_TARGET }}-
    
    - name: Check formatting
      run: mix format --check-formatted
    
    - name: Run Credo
      run: mix credo --strict
    
    - name: Compile
      run: mix compile --warnings-as-errors
    
    - name: Run Dialyzer
      run: mix dialyzer
    
    - name: Run tests with coverage
      run: mix test --cover
